export const SOURCE_COLUMN_MAP = {
  OID_: "oid",
  Register: "register",
  Stratigrap: "stratigraphy",
  Class: "taxClass",
  Order_: "taxOrder",
  Family: "family",
  Taxon: "taxon",
  Taxon_author: "taxonAuthor",
  "Verbatim ID": "verbatimIdentification",
  Type: "typeStatus",
  Cited_Figu: "citedFigure",
  Site: "siteName",
  "Min_Depth (m)": "minDepthM",
  "Max_Depth (m)": "maxDepthM",
  "Province/County/District": "provinceOrDistrict",
  "Community/Region": "region",
  Country: "country",
  Continent_Plate: "continentOrPlate",
  "Water body": "waterBody",
  Ocean_Sea: "oceanSea",
  Latitude: "latitude",
  Longitud: "longitude",
  "Radius (km)": "radiusKm",
  Collection_date: "collectionDateRaw",
  "Date Qualifier": "dateQualifier",
  "Collector/Recorder": "collectorRecorder",
  "Donor / Collection": "donorCollection",
  Indentifie: "identifiedBy",
  Number_of_: "specimenCountRaw",
  Notes: "notes",
  Image_auth: "imageAuthor",
} as const;

export const IMAGE_HEADERS = Array.from({ length: 17 }, (_, index) => `Image${index + 1}`);
export const REFERENCE_HEADERS = Array.from({ length: 4 }, (_, index) => `Reference${index + 1}`);
export const REQUIRED_HEADERS = [
  "OID_",
  "Register",
  "Class",
  "Order_",
  "Family",
  "Taxon",
  "Site",
  "Country",
];
